package com.school.sms.rbac

object Roles {
    const val SUPER_ADMIN = "SUPER_ADMIN"
    const val ADMIN = "ADMIN"
    const val TEACHER = "TEACHER"
    const val STUDENT = "STUDENT"
    const val PARENT = "PARENT"
    const val ACCOUNTANT = "ACCOUNTANT"
    const val LIBRARIAN = "LIBRARIAN"
    val ALL = listOf(SUPER_ADMIN, ADMIN, TEACHER, STUDENT, PARENT, ACCOUNTANT, LIBRARIAN)
}

object Permissions {
    const val MANAGE_USERS = "MANAGE_USERS"
    const val MANAGE_ROLES = "MANAGE_ROLES"
    const val MANAGE_TEACHERS = "MANAGE_TEACHERS"
    const val MANAGE_STUDENTS = "MANAGE_STUDENTS"
    const val MANAGE_PARENTS = "MANAGE_PARENTS"
    const val MANAGE_CLASSES = "MANAGE_CLASSES"
    const val MANAGE_ATTENDANCE = "MANAGE_ATTENDANCE"
    const val MANAGE_EXAMS = "MANAGE_EXAMS"
    const val MANAGE_MARKS = "MANAGE_MARKS"
    const val MANAGE_FEES = "MANAGE_FEES"
    const val MANAGE_ASSIGNMENTS = "MANAGE_ASSIGNMENTS"
    const val MANAGE_LIBRARY = "MANAGE_LIBRARY"
    const val MANAGE_NOTICES = "MANAGE_NOTICES"
    const val VIEW_DASHBOARD = "VIEW_DASHBOARD"
    const val VIEW_REPORTS = "VIEW_REPORTS"
    val ALL = listOf(
        MANAGE_USERS, MANAGE_ROLES, MANAGE_TEACHERS, MANAGE_STUDENTS, MANAGE_PARENTS,
        MANAGE_CLASSES, MANAGE_ATTENDANCE, MANAGE_EXAMS, MANAGE_MARKS, MANAGE_FEES,
        MANAGE_ASSIGNMENTS, MANAGE_LIBRARY, MANAGE_NOTICES, VIEW_DASHBOARD, VIEW_REPORTS
    )
}
